language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t daniberd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daniberd/docker-react npm run test